### PR TITLE
Updated *LOAD, *SAVE.

### PR DESCRIPTION
**Pull request by jgharston**
Combined *LOAD and *SAVE, full address parsing.
FSCALLS test program reporting control block correctly filled.
Will need updating when GSREAD is written, hostfs will also need updating when GSREAD written.
Fixed bug in mainmem.s, file load address set to file load address.

### CODE REVIEW

**Comment by bobbimanners** [comment]
Looking at the delta, I think I will grab your `AUXMEM.OSCLI.S` wholesale.  Should be able to merge it later tonight (Toronto time.)

**Comment by bobbimanners** [comment]
And thank you, as always :)

**Comment by jgharston** [comment]
On 25-08-2021 00:45, Bobbi Webber-Manners wrote:
> Looking at the delta, I think I will grab your AUXMEM.OSCLI.S
> wholesale. Should be able to merge it later tonight (Toronto time.)

I still can't get diffs to work on GitHub, it twlls me everything has 
changed
on every line. :(

All the best. I'm off to bed!

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Merged in `AUXMEM.OSCLI.S` lock stock and barrel.

@jgharston Please grab my latest cos I had to fix a few things for Merlin-8.  It doesn't like hex values and ASC mixed.

No good:
```
ASC 'Blah', $00
```

Good:
```
ASC 'Blah'
DB   $00
```

**Pull request closed without merging**
