### PR TITLE
Fixed bug in loader.s that stopped new chario.s working.

### PR DESCRIPTION
**Pull request by jgharston**

### CODE REVIEW

**Comment by bobbimanners** [comment]
Having trouble working out what to merge.  Your tree is 87 commits behind mind so I don't want to just blindly take your changes and overwrite mine.  There are a few files it is easy to cherrypick (`applecorn.s` has a bug fix - advance EAUXMOS1 by 4K - that is easy to merge.)  But some of the other files like `auxmem.bytwrd.s` have big changes that I need to review if I am going to merge.  I haven't merged your updated `auxmem.vdu.s` and `auxmem.chario.s` from a few days ago because it wasn't working for me (maybe the staging area thing?)  I have been avoiding those files so I can copy yours over mine safely.  The rest I will need your advice and/or to look at the changes very closely.

**Comment by bobbimanners** [comment]
I checked in the fix to `applecorn.po` - bumped up `EAUXMOS1` to $4000.

Looking at `auxmem.chario.s` and `auxmem.vdu.s` right now.

**Comment by bobbimanners** [comment]
And I can confirm that the latest `auxmem.vdu.s` and `auxmem.chario.s` are working with the fix to `EAUXMOS1`.

**Comment by bobbimanners** [comment]
Question - is the cursor supposed to be a flashing `@` ?

**Comment by jgharston** [comment]
wrng lie terminaos

**Pull request closed without merging**
