### PR TITLE
Fixed COPY key bug, tidied *HELP and other bits.

### PR DESCRIPTION
**Pull request by jgharston**
Fixed COPY key bug.
*HELP processes subject, *HELP MOS and *HELP HOSTFS available.
INIT.s OSBYTEs moved.
PR16DEC uses MOS workspace.
Added remaining default vectors.

### CODE REVIEW

**Comment by bobbimanners** [comment]
Will merge this in once I get my `*INFO` stuff finished.

**Comment by bobbimanners** [comment]
Merged.

**Comment by bobbimanners** [comment]
@jgharston 
Annoying thing, this doesn't build in Merlin-16 and I haven't been able to work out exactly what it is complaining about.  I think it doesn't like the circular deps between auxmem.vdu and auxmem.chario maybe.  Whatever order I place them in, it chokes on something.  Maybe you have a better idea than I do what exactly was changed in the most recent commit.

**Comment by bobbimanners** [comment]
[Merlin-16.v3.4.1.Program.po.zip](https://github.com/bobbimanners/Applecorn/files/7149022/Merlin-16.v3.4.1.Program.po.zip)

You may need a GS emulator (needs 65816)

**Comment by jgharston** [comment]
On 12-09-2021 06:12, Bobbi Webber-Manners wrote:
> Merlin-16.v3.4.1.Program.po.zip [1]
> You may need a GS emulator (needs 65816)

Hmmm. I keep getting 27 I/O Error at the moment....

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Error $27 when doing what?

**Comment by jgharston** [comment]
On 12-09-2021 14:54, Bobbi Webber-Manners wrote:
> Error $27 when doing what?

 From the main menu I (L)oad applecorn which goes into the editor.
I then Apple-A to assemble and the screen clears and just displays
$27 I/O Error.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
For Merlin-16 you are trying to run it on an emulated GS?  It needs a 65816.

**Comment by jgharston** [comment]
Can you do a test build with NEGINKEY in CHARIO.S patched as this,
and tell me what INKEY-256 returns for Apple GS ROM 1 and ROM 3.

Ta.

NEGINKEY     CPX   #$01
              LDX   #$00       ; Unimplemented
              BCS   NEGINKEY0

              JSR   NEGCALL    ; Read machine ID from aux

              TAX *TEST*

*             LDX   #$2C
*             TAY
*             BEQ   NEGINKEY0 ;  $00 = Apple IIc -> INKEY-256 = $2C
*             LDX   #$2E
*             AND   #$0F
*             BEQ   NEGINKEY0 ;  $x0 = Apple IIe -> INKEY-256 = $2E
*             LDX   #$2A      ; else = Apple IIgs INKEY-256 = $2A
NEGINKEY0    LDY   #$00
              CLC
              RTS




-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Sure - will do!

**Comment by jgharston** [comment]
On 13-09-2021 14:42, Bobbi Webber-Manners wrote:
> For Merlin-16 you are trying to run it on an emulated GS?
> It needs a 65816.

I'm using KEGS GSplusWin32:  https://apple2.gs/plus/

It could be an emulator problem, as it also has problems running
Applecorn,on starting up it switches to MODE 0 but the display is
full of ***@***.***'s:
http://mdfs.net/Software/BBCBasic/Apple/img/demo09.gif

Using KEGS for Android runns Applecorn fine, but I didn't get very
fas as I can only mount one disk! I think I can eject Merlin once
it's started and insert the Applecorn source, but I hadn't got that
far.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
On any GS (ROM1 or ROM3) you are going to have that display weirdness unless you run a thing called the 'Alternate Text Mode CDA (Classic Desk Accessory)'.  To do this you pop up the control panel using Open Apple + Ctrl + Esc (which I can sometimes make work in GSPort (also KEGS-derived), but not always).  If you don't turn on 'Alternate Text Mode' the graphics memory in banks $00 and $01 do not get shadowed to $E0 and $E1 so you just see whatever garbage is in those banks insteads.  A further quirk is that on ROM1 the 80 column mode using Page2 (which no-one except me uses!) doesn't get shadowed properly even with the CDA enabled, so you have to use 40 cols for now on ROM1.)

**Comment by bobbimanners** [comment]
The eventual fix on ROM1 will be to use 65816 instructions to write to banks $E0 and $E1 directly.  Shadowing is usually preferred because banks $00 and $01 are 2.8MHz and banks $E0 and $E1 are 1MHz.  The GS is a crazy machine!

**Comment by bobbimanners** [comment]
Sorry, up to my eyes in work stuff right now.

**Comment by jgharston** [comment]
On 14-09-2021 14:46, Bobbi Webber-Manners wrote:
> Sorry, up to my eyes in work stuff right now.

That's fine, I've not been able to do anything myself since Friday,
other than scribble some notes. Wake, drive, job, drive, eat, sleep,
wake, drive....
;)

Zoom meeting tonight starting one minute ago, have to go!

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 13-09-2021 23:58, Bobbi Webber-Manners wrote:
> The eventual fix on ROM1 will be to use 65816 instructions to write to
> banks $E0 and $E1 directly. Shadowing is usually preferred because
> banks $00 and $01 are 2.8MHz and banks $E0 and $E1 are 1MHz. The GS is
> a crazy machine!

Do you know how a program can detect if it running a ROM1 Apple?
I've been doing some experimenting, Android KEGS must be emulating
a ROM3 Apple as the display works, it returns $7F from INDENTIFY
at $FE1F. Windows KEGS must be emulating a ROM1 Apple as the display
is full of 2s, but it also returns $7F from IDENTIFY.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
This is the official info:
http://www.1000bit.it/support/manuali/apple/technotes/misc/tn.misc.07.html

**Comment by bobbimanners** [comment]
Oh and this has machine detection ... https://github.com/a2-4am/4cade/blob/master/src/4cade.init.a#L58

**Comment by jgharston** [comment]
Ah, I've suddenly realised, ROM1 and ROM3 aren't different *ROMS*, they
are different *motherboards*. I was wonder how on earth having a
different ROM plugged in would result in not being able to write to
screen memory at the hardware level. It's actually that there are
actually two different motherboard designs, one where the screen
memory is inaccessible, and comes with ROM1 plugged in, and one
where screen memory is accessible and comes with ROM3 plugged in.

Plugging ROM3 into a ROM1 machine won't magically make the screen
memory accessible!

That makes things so much more understandable.

Now I need to learn a bit more 65816 coding to work out how to
do STA &E00800,Y :)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I think as far as Apple were concerned there was the Apple II GS (256KB, originally ROM0 but quickly upgraded to ROM1.)  This was replaced a couple years later by the "Apple II GS with 1MB" ... a totally new board with more memory and ROM3.  So yes, it is not just the ROM that has changed.

I think you jusy need `STAL $E00800,Y` (or set the data bank to $E0 and use `STA 0800,Y`).

**Pull request closed without merging**
