### PR TITLE
Minor tidying of soft key code

### PR DESCRIPTION
**Pull request by jgharston**
Doing *KEY 1 HELLO then pressing Alt-1 was one of those WOW! moments. :)

### CODE REVIEW

**Comment by bobbimanners** [comment]
It is even better on a GS with an Extended ADB keyboard, since that has real function keys :)

**Comment by jgharston** [comment]
On 25-12-2022 03:39, Bobbi Webber-Manners wrote:
> It is even better on a GS with an Extended ADB keyboard, since that
> has real function keys :)

Yes, I was reading through (a very faded scan of) the IIgs hardware
manual a few weeks ago looking into that. My understanding is:

KBDDATA give the normal ASCII code 0-127
KBDMOD  gives shift/ctrl (hurray!), keypad, and others

So you can do:
If '0'-'9'
If bit 4 -> it's a keypad key, convert to 80-89
If bit 0/bit 1 -> modify for Shift/Ctrl.

My IIgs emulator seems to confirm this. If I do:
10 REPEAT
20 A=INKEY(0):IF A<>-1 THEN PRINT ~A,~?&C025
30 UNTIL FALSE

You get the expected values, eg:
31 0 - normal 1
32 0 - normal 2
33 0 - normal 3
31 10 - keypad 1
32 10 - keypad 2
33 10 - keypad 3

Reminds me of my ASCII keyboard I built for my ZX Spectrum:
https://mdfs.net/Docs/Comp/Keyboard/RS2376.htm

etc.
Plus, it will allow INKEY-1, INKEY-2 to be implemented. :)

MERRY CHRISTMAS! :D

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Merry Christmas Jonathan!!  Wishing you all the best for 2023 :)

**Comment by jgharston** [comment]
On 25-12-2022 06:05, Bobbi Webber-Manners wrote:
> Merry Christmas Jonathan!! Wishing you all the best for 2023 :)

Initial work integrating your initial ADH keyboard code:
https://mdfs.net/Software/BBCBasic/Apple/img/demo12.gif

YAY!!!! :D :D :D

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
:christmas_tree:

**Pull request merged**
