### PR TITLE
Updated VDU dispatcher

### PR DESCRIPTION
**Pull request by jgharston**
Also moved VDU OSBYTEs to VDU driver, moved Keyboard OSBYTEs to Keyboard driver.

### CODE REVIEW

**Comment by bobbimanners** [comment]
Will merge this afternoon (once I have debugged something broken in the wildcard stuff)

Thank you.

**Comment by bobbimanners** [comment]
I am in the process of merging this.  Just to warn you I had to clean up some code in `AUXMEM.VDU.S` (and delete a bit of dead code.)  Hopefully I didn't break anything.  Will sanity check, then checkin.

**Comment by jgharston** [comment]
On 09-09-2021 20:45, Bobbi Webber-Manners wrote:
> I am in the process of merging this. Just to warn you I had to clean
> up some code in AUXMEM.VDU.S (and delete a bit of dead code.)
> Hopefully I didn't break anything. Will sanity check, then checkin.

I notice you'd done an update between me cloning and uploading. I did
a diff and couldn't see anything broken.

I'll do another clone later to get up to date.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Merged!

**Comment by jgharston** [comment]
There's also a dynamic debug feature, *OPT 255,n turns debug on/off.
So far, bit 7 displays debug info on errors from the HostFS core in
mainmem, bit 6 displays unrecognised OSBYTE and OSWORD calls. So:

*OPT 255,0 - no debug display (default)
*OPT 255,64 - display unrecognised OSBYTE/OSWORD calls
*OPT 255,128 - display ProDOS error codes
*OPT 255,192 - display unrecognised OSBYTE/OSWORDs and ProDOS errors

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
That will be very handy.  I should add that to the `README.md`.

**Pull request closed without merging**
