### PR TITLE
Optimised *KEY

### PR DESCRIPTION
**Pull request by jgharston**
Also added *SHOW entry, fix for AltGr key + digit which acts as ALT+CTRL.

### CODE REVIEW

**Review by bobbimanners — COMMENTED** [review]
Looks good and no conflicts, so will merge and test :)

**Review by bobbimanners — APPROVED** [review]

**Comment by bobbimanners** [comment]
Function keys are working (Wombat) but still no arrow keys in View or the ISO Pascal Editor.

All the best,
Bobbi

**Comment by jgharston** [comment]
On 31-12-2022 07:16, Bobbi Webber-Manners wrote:
> Function keys are working (Wombat) but still no arrow keys in View or
> the ISO Pascal Editor.

What does KBDTEST report when pressing arrow keys, on their own and
with shift/ctrl/shiftctrl/leftapple/rightapple?

Ta.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
OK, so unshifted:

```
CC  L  L  |!L  Left
CC  M  M  |!M  Right
CC  O  O  |!O  Up
CC  N  N  |!N  Down
```

About to try the others.

**Comment by bobbimanners** [comment]
image

**Comment by bobbimanners** [comment]
The last two sets in the photo above are Open Apple / Closed Apple.

**Comment by jgharston** [comment]
Ok, that shows the keyboard driver is working. It looks like the
*FX4 code has stopped working. I'll have a dig into it after breakfast.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Awesome ... I should go to bed soon :)

**Pull request merged**
