### PR TITLE
More preparation for VDU update.

### PR DESCRIPTION
**Pull request by jgharston**
Moved BYTE75 BYTE76 BYTEA0 to VDU.
KBDINIT returns startup value to pass to VDUINIT.

MAINRDMEM allows code in AUX to read MAIN.
Also allows INKEY-256 to discover machine. PRINT ~INKEY-256 should now return:
&2E - Apple IIe
&2C - Apple IIc
&2A - Apple IIgs

### CODE REVIEW

**Comment by bobbimanners** [comment]
Will give this one a go.  Will probably have to wait until tomorrow (Sunday).

**Comment by bobbimanners** [comment]
I am on it :)

**Comment by bobbimanners** [comment]
It builds and `PRINT ~INKEY-256` works.  However on my //e with 65816 it returns $2A.  There is a way to detect ||gs specifically.  I will ask on A2Infinitum what the canonical way to do it is.  65816 detection may also be useful though!

**Comment by bobbimanners** [comment]
Merged!

**Comment by jgharston** [comment]
On 05-09-2021 11:44, Bobbi Webber-Manners wrote:
> It builds and PRINT ~INKEY-256 works. However on my //e with 65816 it
> returns $2A. There is a way to detect ||gs specifically. I will ask on
> A2Infinitum what the canonical way to do it is. 65816 detection may
> also be useful though!

Yes, I was pondering that. An AppleIIgs "looks like" an Apple IIe
when running 6502 code to be compatible with code expecting to be
running on a IIe, but an Apple IIe can also be using a 65816
processor, so the presence of a 65816 is no guarrantee that you're
on a IIgs.

A 6502/65C02 can never be a IIgs, but a 65816 could possibly be a
IIe/IIc.

After a lot of searching I was surprised I couldn't find any common
code for detecting if you were running on a 65816. After some
experimentation I came up with this:
  http://forum.6502.org/viewtopic.php?f=2&t=2263#p86841

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
This code should work:

*https://github.com/a2-4am/4cade/blob/master/src/4cade.init.a#L58
<https://github.com/a2-4am/4cade/blob/master/src/4cade.init.a#L58>*

The advice I received is to check the 8 bit Machine ID byte first, *before*
calling this.

All the best,
Bobbi

**Comment by jgharston** [comment]
On 06-09-2021 00:35, Bobbi Webber-Manners wrote:
> This code should work:
...
> The advice I received is to check the 8 bit Machine ID byte first,
> *before* calling this.

Ok, I stopped tying to be clever and fiddling with the CPU. :)

Updated INKEY-256 here:
   http://mdfs.net/Software/BBCBasic/Apple/dev/20210906.zip
chario.s - updated NEGINKEY
mainmem.s - added MACHRD

Gives me &2E on AppleWin and &2A on KEGS on my phone.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
> On 06-09-2021 00:35, Bobbi Webber-Manners wrote:
>> The advice I received is to check the 8 bit Machine ID byte first,
>> *before* calling this.

As I understand it, the IIgs ROM1 returns A incorrectly as $1F when
it should be $7F. Is that /always/? Is it impossible for a IIgs to
have MemExpand=No and IWMport=No ?

If so, then that is a robust test for ROM 1 vs ROM 3.
A=$1F -> ROM1
A=$7F -> ROM3

Then that usefully lets us know about the VDU bug - which could be
what I'm seeing on WinKEGS, I'd better try with a different ROM. ;)

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I just merged in some code to support `*ACCESS` (and in so doing found an issue with `*EX`).  I will take a look at your ZIP file shortly and see if it is easy to merge.

**Comment by bobbimanners** [comment]
Actually it is `*ACCESS` I messed up.  `*EX` ought to be more robust to any attributes though, regardless of whether they 'make sense'.

**Comment by jgharston** [comment]
On 06-09-2021 21:51, Bobbi Webber-Manners wrote:
> Actually it is *ACCESS I messed up. *EX ought to be more robust to any
> attributes though, regardless of whether they 'make sense'.

*EX ignores anything other than the W,R and L bits, which are set from
the ProDOS W,R and can't-delete and can't-rename bits, ignoring
everything else.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Those are the bits `*ACCESS` is setting.  In my initial version I messed up the bit setting so I was setting it to something weird like read with nothing else (or maybe write with nothing else.)  `*EX` hung when it got to the affected file and I had to Ctrl-Reset.  After the reset, HostFS was messed up until I `*QUIT` and restarted Applecorn.  It may be worth eyeballing that code to see what could make it hang.  You may also want to look at `SETPERM` in `MAINMEM.S` and see if you agree with me how the ADFS R/W/L maps to the ProDOS bits.

**Comment by bobbimanners** [comment]
Merged your 210806.ZIP.  I get $2E now on the //e with 65816, so looks good :)

**Comment by jgharston** [comment]
On 06-09-2021 23:47, Bobbi Webber-Manners wrote:
> worth eyeballing that code to see what could make it hang. You may
> also want to look at SETPERM in MAINMEM.S and see if you agree with me
> how the ADFS R/W/L maps to the ProDOS bits.

It should map according to the notes in
http://mdfs.net/Software/BBCBasic/Apple/dev/Attrs.txt

I'll have a look when I get home from work.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
Incidentally, in ProDOS/BASIC.SYSTEM there is a more detailed 80 column catalog with full dates (I think):
```
PR #3 : REM TURN ON 80 COLS
CATALOG
```

**Comment by bobbimanners** [comment]
Oh, and on another note ... I finally split up `MAINMEM.S` into more sensible sized pieces.  It was getting out of hand!

**Comment by jgharston** [comment]
On 07-09-2021 16:05, Bobbi Webber-Manners wrote:
> Incidentally, in ProDOS/BASIC.SYSTEM there is a more detailed 80
> column catalog with full dates (I think):

Yes, I was planning on doing something like that, which is why in
MODE 0 (80 columns) I didn't use the extra screen space for two
columns.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 07-09-2021 16:09, Bobbi Webber-Manners wrote:
> directory 'JGH' if it existed. My question is, does it actually check
> it is unique or just take first match? I could test on ADFS but my
> Beeb needs some love right now to get that working again. This also
> comes up in intermediate dirs in the pathname:

If it is an action that can only operate on a single object, it matches
the first match. So, eg LOAD "FRED*" and OSFILE 1-5 matches whichever
of FRED1 FREDDIE FREDERICK appears first in the catalog.

"Single object" also means a diectory within a path, so your example
"/FOO*/BAR*BAZ/N##/HIPPO*" would look in the first object matching
"FOO*" (and error if it's not a directory), then in that directory
look for the first match to "BAR*BAZ" (and error if not a dir) and
in that, etc.

If it is an action that can operate on multiple objects, then the
first match is as above, and then you need another call that remembers
where it has got to and finds the next matching ones. So, like CP/M's
and DOS/Win's 'SearchFirst' and 'SearchNext'. Usually this is just
*ACCESS.

*ACCESS /FOO*/BAR*BAZ/N##/HIPPO* should set access to all the objects
that match "HIPPO*" in the one directory found by matching for
"/FOO*/BAR*BAZ/N##", not all the FOO* directories and all the BAR*BAZ
directories and all the N## directories. Just the end directory.

If it is an action that writes data, it generates a 'Wildcards' error.
So, eg SAVE "FRED*", *DELETE FRED*, *MKDIR FRED*, OPENOUT("FRED*").

Most filing systems give an error with *RENAME FRED* as it is 
computationally
complicated to get a proper wildcarded rename working.

Some filing systems implement *INFO FRED* as a single object match, some
implement it as doing *INFO on all matches.

There is a decision to make as to if '*' matches 'all the rest of the 
name'
or 'all the rest up to any other character'. For instance, whether to
implement such as "FRED*1". I found it really fiddly in HADFS so '*'
just matches to the end of the leafname and doesn't match any further,
but strictly speaking "FRED*1" should skip "FRED" and "FREDDY" and only
match eg "FRED001", "FRED101", "FREDDY1".

Also, strictly speaking "FRED*" should not match "FRED" as "FRED" is
not "FRED and then any additional characters". '*' should be "one or
more of any character" not "zero or more of any character". This is
most likely to be the bit that differs between different 
implementations.

> /FOO*/BAR*BAZ/N##/HIPPO*. Seems like a bit of a pain to implement
> efficiently because I will have to search the dirs and then ProDOS
> will just go do it again.

But as ProDOS doesn't implement wildcards, you'd have to do it anyway
wouldn't you?

You can make the code do shortcuts and if it doesn't find any wildcards
in the pathname don't bother going through the whole path, just pass
it on to ProDOS.

LDX stringlength
.loop
LDA string,X
CMP #'*'
BEQ wild
CMP #'?'
BEQ wild
CMP #'#'
BEQ wild
DEX
BNE loop
RTS ; no wildcards
.wild
; found at least one wildcard, process the whole path

Oh yes, with a "file.ext" filesystem the 'single wildcard'
character is '?', but as '#' appears to be an illegal
character in ProDOS you may as well support it as well.

With a non-tape filing system there's no such concept of
"the next file" that you have on tape, so "" is a bad filename,
so you can easily add a check for this in the path parser:

LDX stringlength
BEQ errBadFilename
.loop
etc.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
On 07-09-2021 16:09, Bobbi Webber-Manners wrote:
> My question is, does it actually check
> it is unique or just take first match?

Re-reading my reply, it's probably simpler just to answer:
* always take the first match regardless of whether anything else would 
match.

Implemented as: search and exit as soon as something matches, or until 
nothing matches.

There's no such error as "*objspec* not unique".

Just as, for example, '*B.' would match *BASIC, *BUILD, *BYE, *BLIST, 
*BROADCAST,
but matches as soon as it finds a match (usually *BASIC) rather than 
searching
every possible command and complaining if more than one would match - 
which
would be horrendous to code for!

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I think I understand how it is supposed to work.  Now to go and actually implement it!

**Comment by bobbimanners** [comment]
I have something implemented that almost works. (`*DIR FOO/BAR/BAZ*XYZ` works but wildcards in the non-leaf node part of the path are not working yet.)

I will try and clean it up and check it in tomorrow.

**Comment by bobbimanners** [comment]
Screenshot from 2021-09-09 11-19-12

**Comment by bobbimanners** [comment]
Getting there!  Need to fix something that got busted and I will check in this wildcard stuff.

**Comment by bobbimanners** [comment]
OK - checked in.  It is only applied for `*DIR` commands right  now.  Gonna start integrating it into `OSFILE` and `OSFIND` ...

**Pull request closed without merging**
