### PR TITLE
Fully integrated ADB keyboard extensions.

### PR DESCRIPTION
**Pull request by jgharston**

### CODE REVIEW

**Comment by bobbimanners** [comment]
Thanks ... but doesn't seem to work so I reverted it for now.

More specifically, everything seems to work except the function keys on my GS using ADB.  (I use a PC USB keyboard and an USB->ADB converter called Wombat from Big Mess 'o' Wires.)

I didn't attempt to debug cos I am in the middle of adding new graphics modes (try `MODE 0` on a GS emulator ... it is just text at the moment though, no graphics yet.  640x200x4 colours.)

**Comment by jgharston** [comment]
On 26-12-2022 23:08, Bobbi Webber-Manners wrote:
> Thanks ... but doesn't seem to work so I reverted it for now.
> More specifically, everything seems to work except the function keys
> on my GS using ADB. (I use a PC USB keyboard and an USB->ADB converter
> called Wombat from Big Mess 'o' Wires.)

I've dug through your code, and see your systems is returning $60+n
for fucntion keys - is that correct? That appears to be the low-level
scan codes, not the key codes. KEGS gives $30+n for keypad keys, it
doesn't appear to give anything for function keys.

Anyway, I've integrated the $60+n code to the ADB translation, though
I can't test it here. I'll upload it to my repository, but not do a
pull request - just fetch the file and report back it it works. When
running KBDTest it will report what keypresses are being reported,
so it should say "f4" when f4 is pressed, etc.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by bobbimanners** [comment]
I more or less coded it by trial and error, but it does work with f-keys and shifted / ctrl f-keys also.

Will give your latest version a spin and report back :)

**Comment by bobbimanners** [comment]
And yes, I think $60+n sounds familiar.

**Comment by bobbimanners** [comment]
Yes, that works!!!  I will commit it :)

**Comment by bobbimanners** [comment]
Done!  Thank you :)

**Pull request merged**
